//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: RpcErrorCode.proto
namespace Qifun.BcpRpc.Test
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RpcTestException")]
  public partial class RpcTestException : global::ProtoBuf.IExtensible
  {
    public RpcTestException() {}
    
    private Qifun.BcpRpc.Test.RpcTestErrorCodes _code = Qifun.BcpRpc.Test.RpcTestErrorCodes.ErrorOne;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Qifun.BcpRpc.Test.RpcTestErrorCodes.ErrorOne)]
    public Qifun.BcpRpc.Test.RpcTestErrorCodes code
    {
      get { return _code; }
      set { _code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"RpcTestErrorCodes")]
    public enum RpcTestErrorCodes
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorOne", Value=1)]
      ErrorOne = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorTwo", Value=2)]
      ErrorTwo = 2
    }
  
}